export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const CATALOG_FETCH_START = "CATALOG_FETCH_START";
export const CATALOG_FETCH_SUCCESS = "CATALOG_FETCH_SUCCESS";
export const CATALOG_FETCH_FAILED = "CATALOG_FETCH_FAILED";

export const CATALOG_SET_ITEMS_PER_PAGE = "CATALOG_SET_ITEMS_PER_PAGE";
export const CATALOG_SET_ITEMS_SORT = "CATALOG_SET_ITEMS_SORT";
export const CATALOG_SET_CURRENT_PAGE = "CATALOG_SET_CURRENT_PAGE";
export const CATALOG_SET_FILTER = "CATALOG_SET_FILTER";
export const CATALOG_SET_ACTIVE_FILTERS = "CATALOG_SET_ACTIVE_FILTERS";
export const CATALOG_SET_AVAILABLE_FILTERS = "CATALOG_SET_AVAILABLE_FILTERS";
export const CATALOG_CLEAR_FILTERS = "CATALOG_CLEAR_FILTERS";

export const REQUEST_CHECKOUT_START = "REQUEST_CHECKOUT_START";
export const REQUEST_CHECKOUT_SUCCESS = "REQUEST_CHECKOUT_SUCCESS";
export const REQUEST_CHECKOUT_FAILED = "REQUEST_CHECKOUT_FAILED";

export const REQUEST_ITEM_ADD = "REQUEST_ITEM_ADD";
export const REQUEST_ITEM_REMOVE = "REQUEST_ITEM_REMOVE";
export const REQUEST_ITEM_CHANGE_COUNT = "REQUEST_ITEM_CHANGE_COUNT";
export const REQUEST_ITEM_PLUS_COUNT = "REQUEST_ITEM_PLUS_COUNT";
export const REQUEST_ITEM_MINUS_COUNT = "REQUEST_ITEM_MINUS_COUNT";
export const REQUEST_FORM_EDIT = "REQUEST_FORM_EDIT";

export const REQUEST_CHANGE_START = "REQUEST_CHANGE_START";
export const REQUEST_EDIT = "REQUEST_EDIT";
export const REQUEST_WITHDRAW = "REQUEST_WITHDRAW";
export const REQUEST_SAVE = "REQUEST_SAVE";
export const REQUEST_SUBMIT = "REQUEST_SUBMIT";
export const REQUEST_DELETE = "REQUEST_DELETE";
export const REQUEST_CHANGE_FAILED = "REQUEST_CHANGE_FAILED";
